version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LojaManoel@2025
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loja-api
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LojaManoelDB;User Id=sa;Password=LojaManoel@2025;TrustServerCertificate=true;
    ports:
      - "5000:80"
    networks:
      - backend
    command: >
      sh -c "dotnet ef database update --no-build &&
             dotnet LojaDoManoel.Service.dll"

volumes:
  sqlserverdata:

networks:
  backend:
