// <auto-generated />
using LojaDoManoel.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaDoManoel.Migrations
{
    [DbContext(typeof(LojaDoManoelContext))]
    [Migration("20250530071426_CreatePedidosAndCaixas")]
    partial class CreatePedidosAndCaixas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaDoManoel.Service.CaixaEntity", b =>
                {
                    b.Property<int>("CaixaEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaixaEntityId"));

                    b.Property<string>("CaixaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Produtos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaixaEntityId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Caixas");
                });

            modelBuilder.Entity("LojaDoManoel.Service.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("LojaDoManoel.Service.CaixaEntity", b =>
                {
                    b.HasOne("LojaDoManoel.Service.Pedido", "Pedido")
                        .WithMany("Caixas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LojaDoManoel.Service.Pedido", b =>
                {
                    b.Navigation("Caixas");
                });
#pragma warning restore 612, 618
        }
    }
}
